name: "Download settings.xml"
on: push
# This is required as per
# https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-cloud-providers#adding-permissions-settings
permissions:
  id-token: write
  contents: read # For repo checkout.
  actions: read # For getting workflow run info.
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: Setup JFrog CLI
          uses: jfrog/setup-jfrog-cli@v4
          env:
            JF_URL: https://f0fa-94-188-248-67.ngrok-free.app
            JF_PROJECT: myproj
          with:
            oidc-provider-name: test
            oidc-audience: testaudi
        - run: |
            jf rt ping
            export JFROG_CLI_LOG_LEVEL=DEBUG
            jf rt dl --fail-no-op --skip-checksum maven-local/settings.xml settings.xml
            cat settings.xml
